### ISSUE TITLE
mkdir errors while running sclo/postgresql-95-centos7

### ISSUE THREAD

**Issue by ashetty1** [sclorg/postgresql-container#154]
I tried deploying sclo/postgresql-94-centos7 on OpenShift , and I see these mkdir permission denied errors:

```
$ oc logs db-1-rrlv8
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```  

I created a pv with the following config:
```
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pv0001

```

Here is the docker-compose that I am using: 
```
version: '2'

services:
  db:
    image: registry.centos.org/sclo/postgresql-95-centos7:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    volumes:
      - /var/lib/pgsql/data
  
  core:
    image: almightycore/almighty-core:latest
    environment:
      ALMIGHTY_POSTGRES_HOST: db
    ports:
      - "8080:8080"

  ui:
    image: surajd/almighty-ui-deploy:demonov8
    ports:
      - "8088:8080"
    environment:
      API_URL: core:8080/api

```
