### ISSUE TITLE
Templates have a buggy liveness probe 

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/postgresql-container#195]
Description copied from original bug report (https://bugzilla.redhat.com/show_bug.cgi?id=1474683)

Templates have the following livenessProbe included:

```
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
```

which lead to the following in the postgress log within the container every 30 sec:

```
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
```

Steps to Reproduce:

```
oc process -f /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.5/db-templates/postgresql-ephemeral-template.json  -v POSTGRESQL_USER=jim -v POSTGRESQL_PASSWORD=redhat -v POSTGRESQL_DATABASE=testdb | oc create -f -
secret "postgresql" created
service "postgresql" created
deploymentconfig "postgresql" created
[root@inf150 ~]# oc get all
NAME            REVISION   DESIRED   CURRENT   TRIGGERED BY
dc/postgresql   1          1         1         config,image(postgresql:9.5)

NAME              DESIRED   CURRENT   READY     AGE
rc/postgresql-1   1         1         1         1m

NAME             CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
svc/postgresql   172.30.83.86   <none>        5432/TCP   1m

NAME                    READY     STATUS    RESTARTS   AGE
po/postgresql-1-2j6sl   1/1       Running   0          57s
[root@inf150 ~]# 
[root@inf150 ~]# oc rsh postgresql-1-2j6sl
sh-4.2$ tail -f /var/lib/pgsql/data/userdata/pg_log/postgresql-Tue.log 
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
```

Actual results:
"LOG:  incomplete startup packet" every 30 seconds in /var/lib/pgsql/data/userdata/pg_log/postgresql-Tue.log 

Expected results:
Our template checks should not cause more logs

Additional info:
Having a look at 
- http://www.postgresql-archive.org/Incomplete-startup-packet-help-needed-td5199030.html

is stating that doing just a tcp connect without sending data at all leads to exactly this message.
The check in our templates is:

```
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
```
which is exactly what is decribed by just doing tcp connect without sending/requesting further input.

A check like the following could prevent the issue:

```
       livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - pg_isready -h 127.0.0.1 -p 5432
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
