### ISSUE TITLE
Build and push action is failing

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/postgresql-container#473]
I've checked the last run of the Build and push action and it fails for some combinations with:
```
Run andstor/file-existence-action@v1
  with:
    files: 12/.exclude-centos7
    ignore_case: false
    follow_symbolic_links: true
    allow_failure: false
  env:
    REGISTRY_AUTH_FILE: /run/user/1001/containers/auth.json
These files don't exist: 12/.exclude-centos7
```
